### ISSUE TITLE
LogViewer problem

### ISSUE THREAD

**Issue by abrca** [WildGums/Orc.Controls#189]
# IF YOU DON'T ANSWER THIS TEMPLATE - THE BOT WILL AUTOMATICALLY CLOSE YOUR ISSUE!

## Please check all of the platforms you are having the issue on (if platform is not listed, it is not supported)

 - [ X] WPF
 - [ ] UWP
 - [ ] iOS
 - [ ] Android
 - [ X] .NET Standard
 - [ ] .NET Core

## Component

What component is this issue occurring in?
LogViewer

## Version of Library
Compiles from sources, downloaded from repository today, 02/May

## Version of OS(s) listed above with issue
Windows 10 x64

## Steps to Reproduce
1. Compile and run Orc.Controls.Example.NET
2. Select "LogViewer" from the left list
3. Catch the exception

## Expected Behavior
Working

## Actual Behavior
Catel.IoC.TypeNotRegisteredException
  HResult=0x80131500
  Сообщение = The specified type 'Orc.Controls.IApplicationLogFilterGroupService, Orc.Controls, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null' is not registered or could not be constructed. Please register type before using it. The type 'Orc.Controls.IApplicationLogFilterGroupService, Orc.Controls, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null' is not registered
  Источник = Catel.Core
  Трассировка стека:
   at Catel.IoC.ServiceLocator.ThrowTypeNotRegisteredException(Type type, String message)
   at Catel.IoC.ServiceLocator.CreateServiceInstanceWrapper(Func`2 createServiceFunc, ServiceLocatorRegistration registration)
   at Catel.IoC.ServiceLocator.ResolveTypeFromKnownContainer(ServiceInfo serviceInfo)
   at Catel.IoC.ServiceLocator.ResolveType(Type serviceType, Object tag)
   at Catel.IoC.TypeFactory.TryCreateToConstruct(Type typeToConstruct, ConstructorInfo constructor, Object tag, Object[] parameters, Boolean checkConstructor, Boolean hasMoreConstructorsLeft, TypeMetaData typeMetaData)
   at Catel.IoC.TypeFactory.CreateInstanceWithSpecifiedParameters(Type typeToConstruct, Object tag, Object[] parameters, Boolean autoCompleteDependencies)
   at Catel.IoC.TypeFactory.CreateInstanceWithTag(Type typeToConstruct, Object tag)
   at Catel.MVVM.ViewModelFactory.CreateViewModel(Type viewModelType, Object dataContext, Object tag)
   at Catel.MVVM.Providers.LogicBase.ConstructViewModelUsingArgumentOrDefaultConstructor(Object injectionObject, Type viewModelType)
   at Catel.MVVM.Providers.UserControlLogic.<UpdateDataContextToUseViewModelAsync>d__69.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Catel.MVVM.Providers.UserControlLogic.<OnTargetViewLoadedAsync>d__56.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Catel.MVVM.Providers.LogicBase.<OnTargetViewLoadedInternal>d__128.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at Orc.Controls.Example.App.Main()

  Изначально это исключение было создано в этом стеке вызовов:
	Catel.IoC.ServiceLocator.ThrowTypeNotRegisteredException(System.Type, string)
	Catel.IoC.ServiceLocator.CreateServiceInstanceWrapper(System.Func<Catel.IoC.ServiceLocatorRegistration, object>, Catel.IoC.ServiceLocatorRegistration)
	Catel.IoC.ServiceLocator.ResolveTypeFromKnownContainer(Catel.IoC.ServiceLocator.ServiceInfo)
	Catel.IoC.ServiceLocator.ResolveType(System.Type, object)
	Catel.IoC.TypeFactory.TryCreateToConstruct(System.Type, System.Reflection.ConstructorInfo, object, object[], bool, bool, Catel.IoC.TypeFactory.TypeMetaData)
	Catel.IoC.TypeFactory.CreateInstanceWithSpecifiedParameters(System.Type, object, object[], bool)
	Catel.IoC.TypeFactory.CreateInstanceWithTag(System.Type, object)
	Catel.MVVM.ViewModelFactory.CreateViewModel(System.Type, object, object)
	Catel.MVVM.Providers.LogicBase.ConstructViewModelUsingArgumentOrDefaultConstructor(object, System.Type)
	Catel.MVVM.Providers.UserControlLogic.UpdateDataContextToUseViewModelAsync(object)
    ...
    [Стек вызовов обрезан]

**Comment by GeertvanHorrik** [comment]
Thanks for reporting, we'll look into this.

**Comment by GeertvanHorrik** [comment]
Please pull the latest, the issue should be resolved. Again, thanks for reporting!
